### ISSUE TITLE
How can I specify end address?

### ISSUE THREAD

**Issue by babaisnyan** [ergrelet/themida-unmutate#4]
It seems I can only specify start address.

**Comment by ergrelet** [comment]
Hi!

I'm not sure why you would want to specify an "end" address? What is the issue you're trying to solve?

**Comment by babaisnyan** [comment]
The script doesn't end. It seems the script reads to end of the file.  Can I specify address of end of the function?

**Comment by babaisnyan** [comment]
The script stops at some point (after 2 hours running)

**Comment by ergrelet** [comment]
Given the output you're getting, Miasm doesn't seem to be able to make sense of the assembly you're pointing to. I don't think that the ability to specify and end address would help extracting anything meaningful out of that.  
What are the addresses you pass pointing at? They should point to obfuscated code entries (i.e., `jmp` instructions that jump to Themida's section).

**Comment by babaisnyan** [comment]
> Given the output you're getting, Miasm doesn't seem to be able to make sense of the assembly you're pointing to. I don't think that the ability to specify an end address would help extracting anything meaningful out of that. What are the addresses you pass to the tool pointing at? They should point to obfuscated code entries (i.e., `jmp` instructions that jump into Themida's section).

When I pass jmp instruction's address the script fails.

INFO - Resolving mutated's functions' addresses...
WARNING - Function doesn't behave as expected, considering it unmutated
Traceback (most recent call last):
  File "themida_unmutate\__main__.py", line 4, in <module>
  File "themida_unmutate\main.py", line 24, in entry_point
  File "themida_unmutate\unwrapping.py", line 18, in unwrap_functions
Exception: Failure to unwrap function
[33120] Failed to execute script '__main__' due to unhandled exception!

**Comment by ergrelet** [comment]
Alright, so as the tool warns you about, this isn't a mutated function. The `pushfd` at the beginning of the routine indicates that the function is virtualized. This tool can only revert Themida's mutation, not its virtualization.
